{% set name = "aioslacker" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 254b727e2d3897e63576f3b7e58b19750c40420124451e1067e33237357e006a

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - aiohttp >=1.3.0
    - slacker <=0.9.42
    - async_timeout >=2.0.0

test:
  imports:
    - aioslacker

about:
  home: https://github.com/aio-libs/aioslacker
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'slacker wrapper for asyncio'
  dev_url: https://github.com/aio-libs/aioslacker

extra:
  recipe-maintainers:
    - synapticarbors
