travis:
  secure:
    BINSTAR_TOKEN: j+iF9H5TS5u3swF0Kb+xCrd889qdGsiBl//wwHynzFhGII6T6sF9wvf6mvX9mTOf/CVV1/FQHmGDOVCQkOvk4fIv8FaQJzqNwZqFjwJotV+xIp95qaSjxyQOnXEjqEZbOJE5BOsZP23fwN1F/DZdU3AA8E42rXAsJHiEiltxJQPU+Fy/I53vFT7g0pICcKJ786wPcmG/5jiGBxv8prrU4Gkk+u0peSYplOot/AJ/v7IgZUSaXVJC3C525mrIXizqai2qXa0D/JtgEwRJeQkhMB1gY923Ag0s0/P6cnFNHCmFcvUWNUVk6OH029GjKvPIEn87E8jIbx6oAccVicmazHslO1BfD+g9v1m8iqtSJY/Tc5VHdM3sbkldyZFDCN0xoHCpLk/MDSj9dd/xkDm6fwfGJVKrcf6FH8VWmBb+m4i4JsUT1Io6vUJmvpPMWGO4rQGLwOipasipzYt2rshHcI4hyF5D5v+BcDR7ENbRE2J3OK4IaPf4gYgAoSqf2hLHUSmj1TdCeVuQ126RIeRK2NB8Q1SB1gZqknkkhu9/Bz2WjW1eEik+YZXTw/1Q1WX04ugz0p+ouFKcx1UgQRwBanoXODv/Gg2nAsnfY5qIKcb166rHTInKSBftleb0CPK+QGYhiHa97HzOm7KjofUuT7guhkQPn8exzHA2DBtKw7A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
